### ISSUE TITLE
State is not minimal

### ISSUE THREAD

**Issue by siddtheone** [bonnie/udemy-TESTING-LIBRARY#10]
https://github.com/bonnie/udemy-TESTING-LIBRARY/blob/9dc4a6778a941a8b26dee49c8e46737c9ee1d04c/finished-projects/sundaes-on-demand/src/contexts/OrderDetails.jsx#L42-L51

I think we should make a util function in which if we pass scoops and toppins count, that should return the final amount.
It can be seperatly tested like we tested color converting function.
The problem with the calculation of price in context is our [state isn't minimal.](https://reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state)

![image](https://user-images.githubusercontent.com/45398971/169706323-2a7e29ee-c8a5-4cc1-8d05-57be90be2e4c.png)

**Comment by bonnie** [comment]
This is a great observation, Siddharth! It is arguably unnecessary to store the derived totals in the context, and instead to provide functions that use [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback) to calculate the totals on the fly.

**Comment by bonnie** [comment]
fixed with streamlined context #13
