### ISSUE TITLE
The lecture cannot be played.

### ISSUE THREAD

**Issue by orchsik** [bonnie/udemy-TESTING-LIBRARY#11]
The lecture cannot be played.
I can't play Udemy's lectures. Not just one lecture, but not many.
I contacted Udemy, but it doesn't work.
I'm sorry for leaving such a post on github, but I want to listen to the lecture.

https://www.udemy.com/course/jest-testing-library/learn/lecture/31621622#questions

**Comment by bonnie** [comment]
Hi, 

Thanks for your interest! Unfortunately, I have no control over Udemy playback. Your best chance of getting this resolved is to keep working with Udemy support. 

Cheers,
Bonnie
