### ISSUE TITLE
userEvent need userEvent.setup()

### ISSUE THREAD

**Issue by hhhminme** [bonnie/udemy-TESTING-LIBRARY#12]
hello. @bonnie ! I'm working on popover testing in section 4 right now.
However, userEvent.click(someElement) is not executed when it is executed like the code in the lecture.

```jsx
test('Initial conditions', () => {
  render(<SummaryForm />);
  const checkbox = screen.getByRole('checkbox', {
    name: /terms and conditions/i,
  });
  //find Checkbox
  expect(checkbox).not.toBeChecked();

  const confirmButton = screen.getByRole('button', { name: /confirm order/i });
  expect(confirmButton).toBeDisabled();
});

test('Checkbox disables button on first click and enables on second click', () => {
  render(<SummaryForm />);

  const checkbox = screen.getByRole('checkbox', {
    name: /terms and conditions/i,
  });

  const confirmButton = screen.getByRole('button', { name: /confirm order/i });

 userEvent.click(checkbox);
  expect(confirmButton).toBeEnabled();

 userEvent.click(checkbox);
  expect(confirmButton).toBeDisabled();
});
```

After digging a little further into the documentation, I found that with asynchronous test execution, I had to do userEvent.click with userEvent.setup() before rendering the component.

## Writing tests with `userEvent`[](https://testing-library.com/docs/user-event/intro#writing-tests-with-userevent)

We recommend invoking `[userEvent.setup()](https://testing-library.com/docs/user-event/setup)` before the component is rendered. This can be done in the test itself, or by using a setup function. We discourage rendering or using any `userEvent` functions outside of the test itself - e.g. in a `before`/`after` hook - for reasons described in ["Avoid Nesting When You're Testing"](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing)

```jsx
import { render, screen } from '@testing-library/react';
import SummaryForm from '../SummaryForm';
import userEvent from '@testing-library/user-event';
test('Initial conditions', () => {
  render(<SummaryForm />);
  const checkbox = screen.getByRole('checkbox', {
    name: /terms and conditions/i,
  });
  //find Checkbox
  expect(checkbox).not.toBeChecked();

  const confirmButton = screen.getByRole('button', { name: /confirm order/i });
  expect(confirmButton).toBeDisabled();
});

test('Checkbox disables button on first click and enables on second click', async () => {
  const user = userEvent.setup();
  render(<SummaryForm />);

  const checkbox = screen.getByRole('checkbox', {
    name: /terms and conditions/i,
  });

  const confirmButton = screen.getByRole('button', { name: /confirm order/i });

  await user.click(checkbox);
  expect(confirmButton).toBeEnabled();

  await user.click(checkbox);
  expect(confirmButton).toBeDisabled();
});
```
I'm wondering if the lecture needs an update or if I'm doing something wrong.

**Comment by bonnie** [comment]
Hi, @hhhminme, 

You are absolutely correct -- the code for userEvent v13 (which is used in the course) is different from the code for userEvent v14 (which you are using). I outline the differences in [WARNING: breaking changes in user-event v14](https://www.udemy.com/course/react-testing-library/learn/lecture/32033540#overview), which include a `setup()` method as you noted. 

I am currently updating the course for (among other things) userEvent v14 and Bootstrap 2.x. For a preview of the new code, see the [2022-sept-updates](https://github.com/bonnie/udemy-TESTING-LIBRARY/tree/2022-sept-updates) branch of this repo. 

If you have further questions, please ask them via Udemy Q&A. 


Cheers,
Bonnie

**Comment by hhhminme** [comment]
Oh! Thank you. I went through the link to the lecture notes you posted, and it's well organized. 

However, I am taking a translated subtitle lecture from Woongjin Thinkbig. Unfortunately, the subtitle lecture is missing a note about userEvent. 

I think there are more people like me in Korea, so I'll ask the Q&A about this. Thank you.

**Comment by bonnie** [comment]
Hi, @hhhminme, 

Thanks for the clarification! This is likely because I added the note after Woongjin had translated the course and I neglected to inform them (my bad). I'll inform them so they can translate the note in the interim before my update is released and gets translated. 

Cheers,
Bonnie
