### ISSUE TITLE
How to start project

### ISSUE THREAD

**Issue by umerjaved178** [bonnie/udemy-TESTING-LIBRARY#3]
Please add proper read.md file, I wamt to start my final exam, that direcotry don't have any package.json, i can't even start it using npm install. 
Please guide

**Comment by bonnie** [comment]
Thanks for reaching out! I added a [README.md](https://github.com/bonnie/udemy-TESTING-LIBRARY/blob/master/lecture-code/README.md) in response to your post to the course Q&A. My assumption was that students would be following along with the course except for possibly skipping the optional lectures, and that it would be easier to copy files in the `src` directory for their existing project than to create a new project and run `npm install`. If you have not been following along with the lectures and need to create a project from scratch, I would recommend creating a new project using [create-react-app](https://create-react-app.dev/), and then using the [package.json from the finished project](https://github.com/bonnie/udemy-TESTING-LIBRARY/blob/master/finished-projects/sundaes-on-demand/package.json).
