### ISSUE TITLE
Mutation

### ISSUE THREAD

**Issue by siddtheone** [bonnie/udemy-TESTING-LIBRARY#9]
https://github.com/bonnie/udemy-TESTING-LIBRARY/blob/9dc4a6778a941a8b26dee49c8e46737c9ee1d04c/finished-projects/sundaes-on-demand/src/contexts/OrderDetails.jsx#L59

I think using .set method will be still be mutation. If you want to change nested value in an object you have to make copy at [each level](https://stackoverflow.com/a/40109764/1102016)

**Comment by bonnie** [comment]
You are correct! Please see [this code comment](https://github.com/bonnie/udemy-TESTING-LIBRARY/blob/9dc4a6778a941a8b26dee49c8e46737c9ee1d04c/finished-projects/sundaes-on-demand/src/contexts/OrderDetails.jsx#L64-L80).
